# Generated by Django 5.1.6 on 2025-02-06 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='duree',
            field=models.IntegerField(default=4, verbose_name="Durée total de l'apprentissage (en nombre de semaine)"),
        ),
    ]
