# Generated by Django 5.1.6 on 2025-02-06 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_cours_duree'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='effort',
            field=models.IntegerField(default=12, verbose_name="Effort à fournir en dehors des heures de cours (en nombre d'heures)"),
        ),
    ]
