# Generated by Django 5.1.6 on 2025-02-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_user_is_registered_inscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='profession',
            field=models.CharField(default="Historien, Enseignant chercheur à L'université de Parakou", max_length=255),
        ),
    ]
