# Generated by Django 5.1.6 on 2025-02-06 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0006_cours_evaluation_certification_cours_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cours',
            name='objectif',
            field=models.CharField(default='Que vous ayez déjà suivi le MOOC de l’an passé ou pas, ce MOOC est fait pour vous afin de rester employable et IA compatible alors que tout va si vite !', max_length=255, verbose_name='En une ou deux phrases, en quoi ce cours sera utile pour la personne qui le suivra ?'),
        ),
    ]
